apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: euyp8ljdd-go
  janus-idp.io/tekton: euyp8ljdd-go
  backstage.io/kubernetes-id: euyp8ljdd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: euyp8ljdd-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
