apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: euyp8ljdd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: euyp8ljdd-go 
  name: euyp8ljdd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: euyp8ljdd-go 
